Renamed option attribute to _option to follow other module federation plugin patterns
Coly010/ng-rspack-build pull request #26
Opened 2024-11-06 11:48 UTC by swalker326

2024-11-06 12:29 UTC, zmzlois commented
this awesome, should we dm Column?

2024-11-06 12:29 UTC, zmzlois commented on packages/build/src/lib/plugins/module-federation/ng-rspack-module-federation-plugin.ts
> +    private _options: ModuleFederationConfig,
nice

2024-11-06 12:29 UTC, zmzlois approved these changes

2024-11-06 15:27 UTC, Coly010 commented
If we're doing this for consistency can we also update the other Plugins in the `build` package?
https://github.com/Coly010/ng-rspack-build/blob/main/packages/build/src/lib/plugins/ng-rspack.ts


https://github.com/Coly010/ng-rspack-build/blob/main/packages/build/src/lib/plugins/module-federation/ng-rspack-module-federation-dev-server-plugin.ts

2024-11-06 15:27 UTC, Coly010 requested changes
See comment above

2024-11-09 13:34 UTC, Coly010 approved these changes
LGTM! Thanks!!

2024-11-09 13:34 UTC, merged